const countries = [
  {
    value: 'Afghanistan',
    html: 'Afghanistan',
    code: 'AF',
    phoneCode: '+93',
    flag: '🇦🇫',
    format: '## ### ####',
  },
  {
    value: 'Åland Islands',
    html: 'Åland Islands',
    code: 'AX',
    phoneCode: '+358',
    flag: '🇦🇽',
    format: '## ### ## ##',
  },
  {
    value: 'Albania',
    html: 'Albania',
    code: 'AL',
    phoneCode: '+355',
    flag: '🇦🇱',
    format: '## ### ####',
  },
  {
    value: 'Algeria',
    html: 'Algeria',
    code: 'DZ',
    phoneCode: '+213',
    flag: '🇩🇿',
    format: '### ## ## ##',
  },
  {
    value: 'American Samoa',
    html: 'American Samoa',
    code: 'AS',
    phoneCode: '+1684',
    flag: '🇦🇸',
    format: '### ####',
  },
  {
    value: 'Andorra',
    html: 'Andorra',
    code: 'AD',
    phoneCode: '+376',
    flag: '🇦🇩',
    format: '### ###',
  },
  {
    value: 'Angola',
    html: 'Angola',
    code: 'AO',
    phoneCode: '+244',
    flag: '🇦🇴',
    format: '### ### ###',
  },
  {
    value: 'Anguilla',
    html: 'Anguilla',
    code: 'AI',
    phoneCode: '+1264',
    flag: '🇦🇮',
    format: '### ####',
  },
  {
    value: 'Antarctica',
    html: 'Antarctica',
    code: 'AQ',
    phoneCode: '+672',
    flag: '🇦🇶',
    format: '# ## ###',
  },
  {
    value: 'Antigua and Barbuda',
    html: 'Antigua and Barbuda',
    code: 'AG',
    phoneCode: '+1268',
    flag: '🇦🇬',
    format: '### ####',
  },
  {
    value: 'Argentina',
    html: 'Argentina',
    code: 'AR',
    phoneCode: '+54',
    flag: '🇦🇷',
    format: '## ####-####',
  },
  {
    value: 'Armenia',
    html: 'Armenia',
    code: 'AM',
    phoneCode: '+374',
    flag: '🇦🇲',
    format: '## ######',
  },
  { value: 'Aruba', html: 'Aruba', code: 'AW', phoneCode: '+297', flag: '🇦🇼', format: '### ####' },
  {
    value: 'Australia',
    html: 'Australia',
    code: 'AU',
    phoneCode: '+61',
    flag: '🇦🇺',
    format: '### ### ###',
  },
  {
    value: 'Austria',
    html: 'Austria',
    code: 'AT',
    phoneCode: '+43',
    flag: '🇦🇹',
    format: '### #######',
  },
  {
    value: 'Azerbaijan',
    html: 'Azerbaijan',
    code: 'AZ',
    phoneCode: '+994',
    flag: '🇦🇿',
    format: '## ### ## ##',
  },
  {
    value: 'Bahamas',
    html: 'Bahamas',
    code: 'BS',
    phoneCode: '+1242',
    flag: '🇧🇸',
    format: '### ####',
  },
  {
    value: 'Bahrain',
    html: 'Bahrain',
    code: 'BH',
    phoneCode: '+973',
    flag: '🇧🇭',
    format: '#### ####',
  },
  {
    value: 'Bangladesh',
    html: 'Bangladesh',
    code: 'BD',
    phoneCode: '+880',
    flag: '🇧🇩',
    format: '####-######',
  },
  {
    value: 'Barbados',
    html: 'Barbados',
    code: 'BB',
    phoneCode: '+1246',
    flag: '🇧🇧',
    format: '### ####',
  },
  {
    value: 'Belarus',
    html: 'Belarus',
    code: 'BY',
    phoneCode: '+375',
    flag: '🇧🇾',
    format: '## ### ##-##',
  },
  {
    value: 'Belgium',
    html: 'Belgium',
    code: 'BE',
    phoneCode: '+32',
    flag: '🇧🇪',
    format: '### ## ## ##',
  },
  {
    value: 'Belize',
    html: 'Belize',
    code: 'BZ',
    phoneCode: '+501',
    flag: '🇧🇿',
    format: '###-####',
  },
  {
    value: 'Benin',
    html: 'Benin',
    code: 'BJ',
    phoneCode: '+229',
    flag: '🇧🇯',
    format: '## ## ## ##',
  },
  {
    value: 'Bermuda',
    html: 'Bermuda',
    code: 'BM',
    phoneCode: '+1441',
    flag: '🇧🇲',
    format: '### ####',
  },
  {
    value: 'Bhutan',
    html: 'Bhutan',
    code: 'BT',
    phoneCode: '+975',
    flag: '🇧🇹',
    format: '## ## ## ##',
  },
  {
    value: 'Bolivia',
    html: 'Bolivia',
    code: 'BO',
    phoneCode: '+591',
    flag: '🇧🇴',
    format: '########',
  },
  {
    value: 'Bosnia and Herzegovina',
    html: 'Bosnia and Herzegovina',
    code: 'BA',
    phoneCode: '+387',
    flag: '🇧🇦',
    format: '## ###-###',
  },
  {
    value: 'Botswana',
    html: 'Botswana',
    code: 'BW',
    phoneCode: '+267',
    flag: '🇧🇼',
    format: '## ### ###',
  },
  {
    value: 'Brazil',
    html: 'Brazil',
    code: 'BR',
    phoneCode: '+55',
    flag: '🇧🇷',
    format: '## #####-####',
  },
  {
    value: 'Brunei Darussalam',
    html: 'Brunei Darussalam',
    code: 'BN',
    phoneCode: '+673',
    flag: '🇧🇳',
    format: '### ####',
  },
  {
    value: 'Bulgaria',
    html: 'Bulgaria',
    code: 'BG',
    phoneCode: '+359',
    flag: '🇧🇬',
    format: '### ### ###',
  },
  {
    value: 'Burkina Faso',
    html: 'Burkina Faso',
    code: 'BF',
    phoneCode: '+226',
    flag: '🇧🇫',
    format: '## ## ## ##',
  },
  {
    value: 'Burundi',
    html: 'Burundi',
    code: 'BI',
    phoneCode: '+257',
    flag: '🇧🇮',
    format: '## ## ## ##',
  },
  {
    value: 'Cabo Verde',
    html: 'Cabo Verde',
    code: 'CV',
    phoneCode: '+238',
    flag: '🇨🇻',
    format: '### ## ##',
  },
  {
    value: 'Cambodia',
    html: 'Cambodia',
    code: 'KH',
    phoneCode: '+855',
    flag: '🇰🇭',
    format: '## ### ###',
  },
  {
    value: 'Cameroon',
    html: 'Cameroon',
    code: 'CM',
    phoneCode: '+237',
    flag: '🇨🇲',
    format: '#### ## ## ##',
  },
  {
    value: 'Canada',
    html: 'Canada',
    code: 'CA',
    phoneCode: '+1',
    flag: '🇨🇦',
    format: '(###) ###-####',
  },
  {
    value: 'Cayman Islands',
    html: 'Cayman Islands',
    code: 'KY',
    phoneCode: '+1345',
    flag: '🇰🇾',
    format: '### ####',
  },
  {
    value: 'Central African Republic',
    html: 'Central African Republic',
    code: 'CF',
    phoneCode: '+236',
    flag: '🇨🇫',
    format: '## ## ## ##',
  },
  { value: 'Chad', html: 'Chad', code: 'TD', phoneCode: '+235', flag: '🇹🇩', format: '## ## ## ##' },
  {
    value: 'Chile',
    html: 'Chile',
    code: 'CL',
    phoneCode: '+56',
    flag: '🇨🇱',
    format: '# #### ####',
  },
  {
    value: 'China',
    html: 'China',
    code: 'CN',
    phoneCode: '+86',
    flag: '🇨🇳',
    format: '### #### ####',
  },
  {
    value: 'Colombia',
    html: 'Colombia',
    code: 'CO',
    phoneCode: '+57',
    flag: '🇨🇴',
    format: '### #######',
  },
  {
    value: 'Comoros',
    html: 'Comoros',
    code: 'KM',
    phoneCode: '+269',
    flag: '🇰🇲',
    format: '## ## ## ##',
  },
  {
    value: 'Congo (Congo-Brazzaville)',
    html: 'Congo (Congo-Brazzaville)',
    code: 'CG',
    phoneCode: '+242',
    flag: '🇨🇬',
    format: '## ### ####',
  },
  {
    value: 'Congo (DRC)',
    html: 'Congo (DRC)',
    code: 'CD',
    phoneCode: '+243',
    flag: '🇨🇩',
    format: '### ### ###',
  },
  {
    value: 'Costa Rica',
    html: 'Costa Rica',
    code: 'CR',
    phoneCode: '+506',
    flag: '🇨🇷',
    format: '#### ####',
  },
  {
    value: 'Croatia',
    html: 'Croatia',
    code: 'HR',
    phoneCode: '+385',
    flag: '🇭🇷',
    format: '## ### ####',
  },
  { value: 'Cuba', html: 'Cuba', code: 'CU', phoneCode: '+53', flag: '🇨🇺', format: '# ### ####' },
  {
    value: 'Cyprus',
    html: 'Cyprus',
    code: 'CY',
    phoneCode: '+357',
    flag: '🇨🇾',
    format: '## ######',
  },
  {
    value: 'Czechia (Czech Republic)',
    html: 'Czechia (Czech Republic)',
    code: 'CZ',
    phoneCode: '+420',
    flag: '🇨🇿',
    format: '### ### ###',
  },
  {
    value: 'Denmark',
    html: 'Denmark',
    code: 'DK',
    phoneCode: '+45',
    flag: '🇩🇰',
    format: '## ## ## ##',
  },
  {
    value: 'Djibouti',
    html: 'Djibouti',
    code: 'DJ',
    phoneCode: '+253',
    flag: '🇩🇯',
    format: '## ## ## ##',
  },
  {
    value: 'Dominica',
    html: 'Dominica',
    code: 'DM',
    phoneCode: '+1767',
    flag: '🇩🇲',
    format: '### ####',
  },
  {
    value: 'Dominican Republic',
    html: 'Dominican Republic',
    code: 'DO',
    phoneCode: '+1809',
    flag: '🇩🇴',
    format: '### ####',
  },
  {
    value: 'Ecuador',
    html: 'Ecuador',
    code: 'EC',
    phoneCode: '+593',
    flag: '🇪🇨',
    format: '## ### ####',
  },
  {
    value: 'Egypt',
    html: 'Egypt',
    code: 'EG',
    phoneCode: '+20',
    flag: '🇪🇬',
    format: '### ### ####',
  },
  {
    value: 'El Salvador',
    html: 'El Salvador',
    code: 'SV',
    phoneCode: '+503',
    flag: '🇸🇻',
    format: '#### ####',
  },
  {
    value: 'Equatorial Guinea',
    html: 'Equatorial Guinea',
    code: 'GQ',
    phoneCode: '+240',
    flag: '🇬🇶',
    format: '### ### ###',
  },
  {
    value: 'Eritrea',
    html: 'Eritrea',
    code: 'ER',
    phoneCode: '+291',
    flag: '🇪🇷',
    format: '# ### ###',
  },
  {
    value: 'Estonia',
    html: 'Estonia',
    code: 'EE',
    phoneCode: '+372',
    flag: '🇪🇪',
    format: '#### ####',
  },
  {
    value: 'Eswatini (fmr. Swaziland)',
    html: 'Eswatini (fmr. Swaziland)',
    code: 'SZ',
    phoneCode: '+268',
    flag: '🇸🇿',
    format: '## ## ####',
  },
  {
    value: 'Ethiopia',
    html: 'Ethiopia',
    code: 'ET',
    phoneCode: '+251',
    flag: '🇪🇹',
    format: '## ### ####',
  },
  { value: 'Fiji', html: 'Fiji', code: 'FJ', phoneCode: '+679', flag: '🇫🇯', format: '### ####' },
  {
    value: 'Finland',
    html: 'Finland',
    code: 'FI',
    phoneCode: '+358',
    flag: '🇫🇮',
    format: '## ### ## ##',
  },
  {
    value: 'France',
    html: 'France',
    code: 'FR',
    phoneCode: '+33',
    flag: '🇫🇷',
    format: '# ## ## ## ##',
  },
  {
    value: 'Gabon',
    html: 'Gabon',
    code: 'GA',
    phoneCode: '+241',
    flag: '🇬🇦',
    format: '## ## ## ##',
  },
  {
    value: 'Gambia',
    html: 'Gambia',
    code: 'GM',
    phoneCode: '+220',
    flag: '🇬🇲',
    format: '### ####',
  },
  {
    value: 'Georgia',
    html: 'Georgia',
    code: 'GE',
    phoneCode: '+995',
    flag: '🇬🇪',
    format: '### ### ###',
  },
  {
    value: 'Germany',
    html: 'Germany',
    code: 'DE',
    phoneCode: '+49',
    flag: '🇩🇪',
    format: '#### #######',
  },
  {
    value: 'Ghana',
    html: 'Ghana',
    code: 'GH',
    phoneCode: '+233',
    flag: '🇬🇭',
    format: '### ### ####',
  },
  {
    value: 'Greece',
    html: 'Greece',
    code: 'GR',
    phoneCode: '+30',
    flag: '🇬🇷',
    format: '### ### ####',
  },
  {
    value: 'Greenland',
    html: 'Greenland',
    code: 'GL',
    phoneCode: '+299',
    flag: '🇬🇱',
    format: '## ## ##',
  },
  {
    value: 'Grenada',
    html: 'Grenada',
    code: 'GD',
    phoneCode: '+1473',
    flag: '🇬🇩',
    format: '### ####',
  },
  {
    value: 'Guatemala',
    html: 'Guatemala',
    code: 'GT',
    phoneCode: '+502',
    flag: '🇬🇹',
    format: '#### ####',
  },
  {
    value: 'Guinea',
    html: 'Guinea',
    code: 'GN',
    phoneCode: '+224',
    flag: '🇬🇳',
    format: '## ### ####',
  },
  {
    value: 'Guinea-Bissau',
    html: 'Guinea-Bissau',
    code: 'GW',
    phoneCode: '+245',
    flag: '🇬🇼',
    format: '### ####',
  },
  {
    value: 'Guyana',
    html: 'Guyana',
    code: 'GY',
    phoneCode: '+592',
    flag: '🇬🇾',
    format: '### ####',
  },
  {
    value: 'Haiti',
    html: 'Haiti',
    code: 'HT',
    phoneCode: '+509',
    flag: '🇭🇹',
    format: '## ## ####',
  },
  {
    value: 'Honduras',
    html: 'Honduras',
    code: 'HN',
    phoneCode: '+504',
    flag: '🇭🇳',
    format: '#### ####',
  },
  {
    value: 'Hungary',
    html: 'Hungary',
    code: 'HU',
    phoneCode: '+36',
    flag: '🇭🇺',
    format: '## ### ####',
  },
  {
    value: 'Iceland',
    html: 'Iceland',
    code: 'IS',
    phoneCode: '+354',
    flag: '🇮🇸',
    format: '### ####',
  },
  {
    value: 'India',
    html: 'India',
    code: 'IN',
    phoneCode: '+91',
    flag: '🇮🇳',
    format: '##### #####',
  },
  {
    value: 'Indonesia',
    html: 'Indonesia',
    code: 'ID',
    phoneCode: '+62',
    flag: '🇮🇩',
    format: '###-###-####',
  },
  { value: 'Iran', html: 'Iran', code: 'IR', phoneCode: '+98', flag: '🇮🇷', format: '### ### ####' },
  {
    value: 'Iraq',
    html: 'Iraq',
    code: 'IQ',
    phoneCode: '+964',
    flag: '🇮🇶',
    format: '### ### ####',
  },
  {
    value: 'Ireland',
    html: 'Ireland',
    code: 'IE',
    phoneCode: '+353',
    flag: '🇮🇪',
    format: '## ### ####',
  },
  {
    value: 'Israel',
    html: 'Israel',
    code: 'IL',
    phoneCode: '+972',
    flag: '🇮🇱',
    format: '##-###-####',
  },
  {
    value: 'Italy',
    html: 'Italy',
    code: 'IT',
    phoneCode: '+39',
    flag: '🇮🇹',
    format: '### ### ####',
  },
  {
    value: 'Jamaica',
    html: 'Jamaica',
    code: 'JM',
    phoneCode: '+1876',
    flag: '🇯🇲',
    format: '### ####',
  },
  {
    value: 'Japan',
    html: 'Japan',
    code: 'JP',
    phoneCode: '+81',
    flag: '🇯🇵',
    format: '##-####-####',
  },
  {
    value: 'Jordan',
    html: 'Jordan',
    code: 'JO',
    phoneCode: '+962',
    flag: '🇯🇴',
    format: '# #### ####',
  },
  {
    value: 'Kazakhstan',
    html: 'Kazakhstan',
    code: 'KZ',
    phoneCode: '+7',
    flag: '🇰🇿',
    format: '### ###-##-##',
  },
  {
    value: 'Kenya',
    html: 'Kenya',
    code: 'KE',
    phoneCode: '+254',
    flag: '🇰🇪',
    format: '### ######',
  },
  {
    value: 'Kiribati',
    html: 'Kiribati',
    code: 'KI',
    phoneCode: '+686',
    flag: '🇰🇮',
    format: '## ###',
  },
  {
    value: 'Korea (North)',
    html: 'Korea (North)',
    code: 'KP',
    phoneCode: '+850',
    flag: '🇰🇵',
    format: '### ### ####',
  },
  {
    value: 'Korea (South)',
    html: 'Korea (South)',
    code: 'KR',
    phoneCode: '+82',
    flag: '🇰🇷',
    format: '##-####-####',
  },
  {
    value: 'Kuwait',
    html: 'Kuwait',
    code: 'KW',
    phoneCode: '+965',
    flag: '🇰🇼',
    format: '#### ####',
  },
  {
    value: 'Kyrgyzstan',
    html: 'Kyrgyzstan',
    code: 'KG',
    phoneCode: '+996',
    flag: '🇰🇬',
    format: '### ### ###',
  },
  {
    value: 'Laos',
    html: 'Laos',
    code: 'LA',
    phoneCode: '+856',
    flag: '🇱🇦',
    format: '## ## ### ###',
  },
  {
    value: 'Latvia',
    html: 'Latvia',
    code: 'LV',
    phoneCode: '+371',
    flag: '🇱🇻',
    format: '## ### ###',
  },
  {
    value: 'Lebanon',
    html: 'Lebanon',
    code: 'LB',
    phoneCode: '+961',
    flag: '🇱🇧',
    format: '## ### ###',
  },
  {
    value: 'Lesotho',
    html: 'Lesotho',
    code: 'LS',
    phoneCode: '+266',
    flag: '🇱🇸',
    format: '## ### ###',
  },
  {
    value: 'Liberia',
    html: 'Liberia',
    code: 'LR',
    phoneCode: '+231',
    flag: '🇱🇷',
    format: '### ### ####',
  },
  {
    value: 'Libya',
    html: 'Libya',
    code: 'LY',
    phoneCode: '+218',
    flag: '🇱🇾',
    format: '##-#######',
  },
  {
    value: 'Liechtenstein',
    html: 'Liechtenstein',
    code: 'LI',
    phoneCode: '+423',
    flag: '🇱🇮',
    format: '### ####',
  },
  {
    value: 'Lithuania',
    html: 'Lithuania',
    code: 'LT',
    phoneCode: '+370',
    flag: '🇱🇹',
    format: '### #####',
  },
  {
    value: 'Luxembourg',
    html: 'Luxembourg',
    code: 'LU',
    phoneCode: '+352',
    flag: '🇱🇺',
    format: '### ### ###',
  },
  {
    value: 'Madagascar',
    html: 'Madagascar',
    code: 'MG',
    phoneCode: '+261',
    flag: '🇲🇬',
    format: '## ## ### ##',
  },
  {
    value: 'Malawi',
    html: 'Malawi',
    code: 'MW',
    phoneCode: '+265',
    flag: '🇲🇼',
    format: '### ## ## ##',
  },
  {
    value: 'Malaysia',
    html: 'Malaysia',
    code: 'MY',
    phoneCode: '+60',
    flag: '🇲🇾',
    format: '##-### ####',
  },
  {
    value: 'Maldives',
    html: 'Maldives',
    code: 'MV',
    phoneCode: '+960',
    flag: '🇲🇻',
    format: '###-####',
  },
  { value: 'Mali', html: 'Mali', code: 'ML', phoneCode: '+223', flag: '🇲🇱', format: '## ## ## ##' },
  { value: 'Malta', html: 'Malta', code: 'MT', phoneCode: '+356', flag: '🇲🇹', format: '#### ####' },
  {
    value: 'Marshall Islands',
    html: 'Marshall Islands',
    code: 'MH',
    phoneCode: '+692',
    flag: '🇲🇭',
    format: '### ####',
  },
  {
    value: 'Mauritania',
    html: 'Mauritania',
    code: 'MR',
    phoneCode: '+222',
    flag: '🇲🇷',
    format: '## ## ## ##',
  },
  {
    value: 'Mauritius',
    html: 'Mauritius',
    code: 'MU',
    phoneCode: '+230',
    flag: '🇲🇺',
    format: '### ####',
  },
  {
    value: 'Mexico',
    html: 'Mexico',
    code: 'MX',
    phoneCode: '+52',
    flag: '🇲🇽',
    format: '### ### ####',
  },
  {
    value: 'Micronesia',
    html: 'Micronesia',
    code: 'FM',
    phoneCode: '+691',
    flag: '🇫🇲',
    format: '### ####',
  },
  {
    value: 'Moldova',
    html: 'Moldova',
    code: 'MD',
    phoneCode: '+373',
    flag: '🇲🇩',
    format: '### ## ###',
  },
  {
    value: 'Monaco',
    html: 'Monaco',
    code: 'MC',
    phoneCode: '+377',
    flag: '🇲🇨',
    format: '## ## ## ## ##',
  },
  {
    value: 'Mongolia',
    html: 'Mongolia',
    code: 'MN',
    phoneCode: '+976',
    flag: '🇲🇳',
    format: '#### ####',
  },
  {
    value: 'Montenegro',
    html: 'Montenegro',
    code: 'ME',
    phoneCode: '+382',
    flag: '🇲🇪',
    format: '## ### ###',
  },
  {
    value: 'Morocco',
    html: 'Morocco',
    code: 'MA',
    phoneCode: '+212',
    flag: '🇲🇦',
    format: '###-######',
  },
  {
    value: 'Mozambique',
    html: 'Mozambique',
    code: 'MZ',
    phoneCode: '+258',
    flag: '🇲🇿',
    format: '## ### ####',
  },
  {
    value: 'Myanmar',
    html: 'Myanmar',
    code: 'MM',
    phoneCode: '+95',
    flag: '🇲🇲',
    format: '## ### ####',
  },
  {
    value: 'Namibia',
    html: 'Namibia',
    code: 'NA',
    phoneCode: '+264',
    flag: '🇳🇦',
    format: '## ### ####',
  },
  { value: 'Nauru', html: 'Nauru', code: 'NR', phoneCode: '+674', flag: '🇳🇷', format: '### ####' },
  {
    value: 'Nepal',
    html: 'Nepal',
    code: 'NP',
    phoneCode: '+977',
    flag: '🇳🇵',
    format: '##-########',
  },
  {
    value: 'Netherlands',
    html: 'Netherlands',
    code: 'NL',
    phoneCode: '+31',
    flag: '🇳🇱',
    format: '## ########',
  },
  {
    value: 'New Zealand',
    html: 'New Zealand',
    code: 'NZ',
    phoneCode: '+64',
    flag: '🇳🇿',
    format: '## ### ####',
  },
  {
    value: 'Nicaragua',
    html: 'Nicaragua',
    code: 'NI',
    phoneCode: '+505',
    flag: '🇳🇮',
    format: '#### ####',
  },
  {
    value: 'Niger',
    html: 'Niger',
    code: 'NE',
    phoneCode: '+227',
    flag: '🇳🇪',
    format: '## ## ## ##',
  },
  {
    value: 'Nigeria',
    html: 'Nigeria',
    code: 'NG',
    phoneCode: '+234',
    flag: '🇳🇬',
    format: '### ### ####',
  },
  {
    value: 'Norway',
    html: 'Norway',
    code: 'NO',
    phoneCode: '+47',
    flag: '🇳🇴',
    format: '### ## ###',
  },
  { value: 'Oman', html: 'Oman', code: 'OM', phoneCode: '+968', flag: '🇴🇲', format: '#### ####' },
  {
    value: 'Pakistan',
    html: 'Pakistan',
    code: 'PK',
    phoneCode: '+92',
    flag: '🇵🇰',
    format: '### #######',
  },
  { value: 'Palau', html: 'Palau', code: 'PW', phoneCode: '+680', flag: '🇵🇼', format: '### ####' },
  {
    value: 'Palestine, State of',
    html: 'Palestine, State of',
    code: 'PS',
    phoneCode: '+970',
    flag: '🇵🇸',
    format: '### ### ###',
  },
  {
    value: 'Panama',
    html: 'Panama',
    code: 'PA',
    phoneCode: '+507',
    flag: '🇵🇦',
    format: '####-####',
  },
  {
    value: 'Papua New Guinea',
    html: 'Papua New Guinea',
    code: 'PG',
    phoneCode: '+675',
    flag: '🇵🇬',
    format: '### ####',
  },
  {
    value: 'Paraguay',
    html: 'Paraguay',
    code: 'PY',
    phoneCode: '+595',
    flag: '🇵🇾',
    format: '### ######',
  },
  { value: 'Peru', html: 'Peru', code: 'PE', phoneCode: '+51', flag: '🇵🇪', format: '### ### ###' },
  {
    value: 'Philippines',
    html: 'Philippines',
    code: 'PH',
    phoneCode: '+63',
    flag: '🇵🇭',
    format: '### ### ####',
  },
  {
    value: 'Poland',
    html: 'Poland',
    code: 'PL',
    phoneCode: '+48',
    flag: '🇵🇱',
    format: '### ### ###',
  },
  {
    value: 'Portugal',
    html: 'Portugal',
    code: 'PT',
    phoneCode: '+351',
    flag: '🇵🇹',
    format: '### ### ###',
  },
  { value: 'Qatar', html: 'Qatar', code: 'QA', phoneCode: '+974', flag: '🇶🇦', format: '#### ####' },
  {
    value: 'Romania',
    html: 'Romania',
    code: 'RO',
    phoneCode: '+40',
    flag: '🇷🇴',
    format: '### ### ###',
  },
  {
    value: 'Russia',
    html: 'Russia',
    code: 'RU',
    phoneCode: '+7',
    flag: '🇷🇺',
    format: '### ###-##-##',
  },
  {
    value: 'Rwanda',
    html: 'Rwanda',
    code: 'RW',
    phoneCode: '+250',
    flag: '🇷🇼',
    format: '### ### ###',
  },
  {
    value: 'Saint Kitts and Nevis',
    html: 'Saint Kitts and Nevis',
    code: 'KN',
    phoneCode: '+1869',
    flag: '🇰🇳',
    format: '### ####',
  },
  {
    value: 'Saint Lucia',
    html: 'Saint Lucia',
    code: 'LC',
    phoneCode: '+1758',
    flag: '🇱🇨',
    format: '### ####',
  },
  {
    value: 'Saint Vincent and the Grenadines',
    html: 'Saint Vincent and the Grenadines',
    code: 'VC',
    phoneCode: '+1784',
    flag: '🇻🇨',
    format: '### ####',
  },
  { value: 'Samoa', html: 'Samoa', code: 'WS', phoneCode: '+685', flag: '🇼🇸', format: '## ####' },
  {
    value: 'San Marino',
    html: 'San Marino',
    code: 'SM',
    phoneCode: '+378',
    flag: '🇸🇲',
    format: '#### ######',
  },
  {
    value: 'Sao Tome and Principe',
    html: 'Sao Tome and Principe',
    code: 'ST',
    phoneCode: '+239',
    flag: '🇸🇹',
    format: '### ####',
  },
  {
    value: 'Saudi Arabia',
    html: 'Saudi Arabia',
    code: 'SA',
    phoneCode: '+966',
    flag: '🇸🇦',
    format: '## ### ####',
  },
  {
    value: 'Senegal',
    html: 'Senegal',
    code: 'SN',
    phoneCode: '+221',
    flag: '🇸🇳',
    format: '## ### ## ##',
  },
  {
    value: 'Serbia',
    html: 'Serbia',
    code: 'RS',
    phoneCode: '+381',
    flag: '🇷🇸',
    format: '## ### ####',
  },
  {
    value: 'Seychelles',
    html: 'Seychelles',
    code: 'SC',
    phoneCode: '+248',
    flag: '🇸🇨',
    format: '# ### ###',
  },
  {
    value: 'Sierra Leone',
    html: 'Sierra Leone',
    code: 'SL',
    phoneCode: '+232',
    flag: '🇸🇱',
    format: '## ######',
  },
  {
    value: 'Singapore',
    html: 'Singapore',
    code: 'SG',
    phoneCode: '+65',
    flag: '🇸🇬',
    format: '#### ####',
  },
  {
    value: 'Slovakia',
    html: 'Slovakia',
    code: 'SK',
    phoneCode: '+421',
    flag: '🇸🇰',
    format: '### ### ###',
  },
  {
    value: 'Slovenia',
    html: 'Slovenia',
    code: 'SI',
    phoneCode: '+386',
    flag: '🇸🇮',
    format: '## ### ###',
  },
  {
    value: 'Solomon Islands',
    html: 'Solomon Islands',
    code: 'SB',
    phoneCode: '+677',
    flag: '🇸🇧',
    format: '### ####',
  },
  {
    value: 'Somalia',
    html: 'Somalia',
    code: 'SO',
    phoneCode: '+252',
    flag: '🇸🇴',
    format: '## ### ####',
  },
  {
    value: 'South Africa',
    html: 'South Africa',
    code: 'ZA',
    phoneCode: '+27',
    flag: '🇿🇦',
    format: '## ### ####',
  },
  {
    value: 'South Sudan',
    html: 'South Sudan',
    code: 'SS',
    phoneCode: '+211',
    flag: '🇸🇸',
    format: '### ### ###',
  },
  {
    value: 'Spain',
    html: 'Spain',
    code: 'ES',
    phoneCode: '+34',
    flag: '🇪🇸',
    format: '### ### ###',
  },
  {
    value: 'Sri Lanka',
    html: 'Sri Lanka',
    code: 'LK',
    phoneCode: '+94',
    flag: '🇱🇰',
    format: '## ### ####',
  },
  {
    value: 'Sudan',
    html: 'Sudan',
    code: 'SD',
    phoneCode: '+249',
    flag: '🇸🇩',
    format: '## ### ####',
  },
  {
    value: 'Suriname',
    html: 'Suriname',
    code: 'SR',
    phoneCode: '+597',
    flag: '🇸🇷',
    format: '###-####',
  },
  {
    value: 'Sweden',
    html: 'Sweden',
    code: 'SE',
    phoneCode: '+46',
    flag: '🇸🇪',
    format: '##-### ## ##',
  },
  {
    value: 'Switzerland',
    html: 'Switzerland',
    code: 'CH',
    phoneCode: '+41',
    flag: '🇨🇭',
    format: '## ### ## ##',
  },
  {
    value: 'Syria',
    html: 'Syria',
    code: 'SY',
    phoneCode: '+963',
    flag: '🇸🇾',
    format: '### ### ###',
  },
  {
    value: 'Taiwan',
    html: 'Taiwan',
    code: 'TW',
    phoneCode: '+886',
    flag: '🇹🇼',
    format: '### ### ###',
  },
  {
    value: 'Tajikistan',
    html: 'Tajikistan',
    code: 'TJ',
    phoneCode: '+992',
    flag: '🇹🇯',
    format: '## ### ####',
  },
  {
    value: 'Tanzania',
    html: 'Tanzania',
    code: 'TZ',
    phoneCode: '+255',
    flag: '🇹🇿',
    format: '### ### ###',
  },
  {
    value: 'Thailand',
    html: 'Thailand',
    code: 'TH',
    phoneCode: '+66',
    flag: '🇹🇭',
    format: '##-###-####',
  },
  {
    value: 'Timor-Leste',
    html: 'Timor-Leste',
    code: 'TL',
    phoneCode: '+670',
    flag: '🇹🇱',
    format: '### ####',
  },
  { value: 'Togo', html: 'Togo', code: 'TG', phoneCode: '+228', flag: '🇹🇬', format: '## ## ## ##' },
  { value: 'Tonga', html: 'Tonga', code: 'TO', phoneCode: '+676', flag: '🇹🇴', format: '### ####' },
  {
    value: 'Trinidad and Tobago',
    html: 'Trinidad and Tobago',
    code: 'TT',
    phoneCode: '+1868',
    flag: '🇹🇹',
    format: '### ####',
  },
  {
    value: 'Tunisia',
    html: 'Tunisia',
    code: 'TN',
    phoneCode: '+216',
    flag: '🇹🇳',
    format: '## ### ###',
  },
  {
    value: 'Turkey',
    html: 'Turkey',
    code: 'TR',
    phoneCode: '+90',
    flag: '🇹🇷',
    format: '### ### ## ##',
  },
  {
    value: 'Turkmenistan',
    html: 'Turkmenistan',
    code: 'TM',
    phoneCode: '+993',
    flag: '🇹🇲',
    format: '## ######',
  },
  { value: 'Tuvalu', html: 'Tuvalu', code: 'TV', phoneCode: '+688', flag: '🇹🇻', format: '#####' },
  {
    value: 'Uganda',
    html: 'Uganda',
    code: 'UG',
    phoneCode: '+256',
    flag: '🇺🇬',
    format: '### ######',
  },
  {
    value: 'Ukraine',
    html: 'Ukraine',
    code: 'UA',
    phoneCode: '+380',
    flag: '🇺🇦',
    format: '## ### ####',
  },
  {
    value: 'United Arab Emirates',
    html: 'United Arab Emirates',
    code: 'AE',
    phoneCode: '+971',
    flag: '🇦🇪',
    format: '## ### ####',
  },
  {
    value: 'United Kingdom',
    html: 'United Kingdom',
    code: 'GB',
    phoneCode: '+44',
    flag: '🇬🇧',
    format: '#### ######',
  },
  {
    value: 'United States',
    html: 'United States',
    code: 'US',
    phoneCode: '+1',
    flag: '🇺🇸',
    format: '(###) ###-####',
  },
  {
    value: 'Uruguay',
    html: 'Uruguay',
    code: 'UY',
    phoneCode: '+598',
    flag: '🇺🇾',
    format: '## ### ####',
  },
  {
    value: 'Uzbekistan',
    html: 'Uzbekistan',
    code: 'UZ',
    phoneCode: '+998',
    flag: '🇺🇿',
    format: '## ### ####',
  },
  {
    value: 'Vanuatu',
    html: 'Vanuatu',
    code: 'VU',
    phoneCode: '+678',
    flag: '🇻🇺',
    format: '### ####',
  },
  {
    value: 'Venezuela',
    html: 'Venezuela',
    code: 'VE',
    phoneCode: '+58',
    flag: '🇻🇪',
    format: '###-#######',
  },
  {
    value: 'Vietnam',
    html: 'Vietnam',
    code: 'VN',
    phoneCode: '+84',
    flag: '🇻🇳',
    format: '### ### ####',
  },
  {
    value: 'Yemen',
    html: 'Yemen',
    code: 'YE',
    phoneCode: '+967',
    flag: '🇾🇪',
    format: '### ### ###',
  },
  {
    value: 'Zambia',
    html: 'Zambia',
    code: 'ZM',
    phoneCode: '+260',
    flag: '🇿🇲',
    format: '### #######',
  },
  {
    value: 'Zimbabwe',
    html: 'Zimbabwe',
    code: 'ZW',
    phoneCode: '+263',
    flag: '🇿🇼',
    format: '## ### ####',
  },
]

export default countries
