const countries = [
  { value: 'Afghanistan', html: 'Afghanistan', code: 'AF' },
  { value: 'Åland Islands', html: 'Åland Islands', code: 'AX' },
  { value: 'Albania', html: 'Albania', code: 'AL' },
  { value: 'Algeria', html: 'Algeria', code: 'DZ' },
  { value: 'American Samoa', html: 'American Samoa', code: 'AS' },
  { value: 'Andorra', html: 'Andorra', code: 'AD' },
  { value: 'Angola', html: 'Angola', code: 'AO' },
  { value: 'Anguilla', html: 'Anguilla', code: 'AI' },
  { value: 'Antarctica', html: 'Antarctica', code: 'AQ' },
  { value: 'Antigua and Barbuda', html: 'Antigua and Barbuda', code: 'AG' },
  { value: 'Argentina', html: 'Argentina', code: 'AR' },
  { value: 'Armenia', html: 'Armenia', code: 'AM' },
  { value: 'Aruba', html: 'Aruba', code: 'AW' },
  { value: 'Australia', html: 'Australia', code: 'AU' },
  { value: 'Austria', html: 'Austria', code: 'AT' },
  { value: 'Azerbaijan', html: 'Azerbaijan', code: 'AZ' },
  { value: 'Bahamas', html: 'Bahamas', code: 'BS' },
  { value: 'Bahrain', html: 'Bahrain', code: 'BH' },
  { value: 'Bangladesh', html: 'Bangladesh', code: 'BD' },
  { value: 'Barbados', html: 'Barbados', code: 'BB' },
  { value: 'Belarus', html: 'Belarus', code: 'BY' },
  { value: 'Belgium', html: 'Belgium', code: 'BE' },
  { value: 'Belize', html: 'Belize', code: 'BZ' },
  { value: 'Benin', html: 'Benin', code: 'BJ' },
  { value: 'Bermuda', html: 'Bermuda', code: 'BM' },
  { value: 'Bhutan', html: 'Bhutan', code: 'BT' },
  { value: 'Bolivia', html: 'Bolivia', code: 'BO' },
  {
    value: 'Bosnia and Herzegovina',
    html: 'Bosnia and Herzegovina',
    code: 'BA',
  },
  { value: 'Botswana', html: 'Botswana', code: 'BW' },
  { value: 'Brazil', html: 'Brazil', code: 'BR' },
  { value: 'Brunei Darussalam', html: 'Brunei Darussalam', code: 'BN' },
  { value: 'Bulgaria', html: 'Bulgaria', code: 'BG' },
  { value: 'Burkina Faso', html: 'Burkina Faso', code: 'BF' },
  { value: 'Burundi', html: 'Burundi', code: 'BI' },
  { value: 'Cabo Verde', html: 'Cabo Verde', code: 'CV' },
  { value: 'Cambodia', html: 'Cambodia', code: 'KH' },
  { value: 'Cameroon', html: 'Cameroon', code: 'CM' },
  { value: 'Canada', html: 'Canada', code: 'CA' },
  { value: 'Cayman Islands', html: 'Cayman Islands', code: 'KY' },
  {
    value: 'Central African Republic',
    html: 'Central African Republic',
    code: 'CF',
  },
  { value: 'Chad', html: 'Chad', code: 'TD' },
  { value: 'Chile', html: 'Chile', code: 'CL' },
  { value: 'China', html: 'China', code: 'CN' },
  { value: 'Colombia', html: 'Colombia', code: 'CO' },
  { value: 'Comoros', html: 'Comoros', code: 'KM' },
  {
    value: 'Congo (Congo-Brazzaville)',
    html: 'Congo (Congo-Brazzaville)',
    code: 'CG',
  },
  { value: 'Congo (DRC)', html: 'Congo (DRC)', code: 'CD' },
  { value: 'Costa Rica', html: 'Costa Rica', code: 'CR' },
  { value: 'Croatia', html: 'Croatia', code: 'HR' },
  { value: 'Cuba', html: 'Cuba', code: 'CU' },
  { value: 'Cyprus', html: 'Cyprus', code: 'CY' },
  {
    value: 'Czechia (Czech Republic)',
    html: 'Czechia (Czech Republic)',
    code: 'CZ',
  },
  { value: 'Denmark', html: 'Denmark', code: 'DK' },
  { value: 'Djibouti', html: 'Djibouti', code: 'DJ' },
  { value: 'Dominica', html: 'Dominica', code: 'DM' },
  { value: 'Dominican Republic', html: 'Dominican Republic', code: 'DO' },
  { value: 'Ecuador', html: 'Ecuador', code: 'EC' },
  { value: 'Egypt', html: 'Egypt', code: 'EG' },
  { value: 'El Salvador', html: 'El Salvador', code: 'SV' },
  { value: 'Equatorial Guinea', html: 'Equatorial Guinea', code: 'GQ' },
  { value: 'Eritrea', html: 'Eritrea', code: 'ER' },
  { value: 'Estonia', html: 'Estonia', code: 'EE' },
  {
    value: 'Eswatini (fmr. Swaziland)',
    html: 'Eswatini (fmr. Swaziland)',
    code: 'SZ',
  },
  { value: 'Ethiopia', html: 'Ethiopia', code: 'ET' },
  { value: 'Fiji', html: 'Fiji', code: 'FJ' },
  { value: 'Finland', html: 'Finland', code: 'FI' },
  { value: 'France', html: 'France', code: 'FR' },
  { value: 'Gabon', html: 'Gabon', code: 'GA' },
  { value: 'Gambia', html: 'Gambia', code: 'GM' },
  { value: 'Georgia', html: 'Georgia', code: 'GE' },
  { value: 'Germany', html: 'Germany', code: 'DE' },
  { value: 'Ghana', html: 'Ghana', code: 'GH' },
  { value: 'Greece', html: 'Greece', code: 'GR' },
  { value: 'Greenland', html: 'Greenland', code: 'GL' },
  { value: 'Grenada', html: 'Grenada', code: 'GD' },
  { value: 'Guatemala', html: 'Guatemala', code: 'GT' },
  { value: 'Guinea', html: 'Guinea', code: 'GN' },
  { value: 'Guinea-Bissau', html: 'Guinea-Bissau', code: 'GW' },
  { value: 'Guyana', html: 'Guyana', code: 'GY' },
  { value: 'Haiti', html: 'Haiti', code: 'HT' },
  { value: 'Honduras', html: 'Honduras', code: 'HN' },
  { value: 'Hungary', html: 'Hungary', code: 'HU' },
  { value: 'Iceland', html: 'Iceland', code: 'IS' },
  { value: 'India', html: 'India', code: 'IN' },
  { value: 'Indonesia', html: 'Indonesia', code: 'ID' },
  { value: 'Iran', html: 'Iran', code: 'IR' },
  { value: 'Iraq', html: 'Iraq', code: 'IQ' },
  { value: 'Ireland', html: 'Ireland', code: 'IE' },
  { value: 'Israel', html: 'Israel', code: 'IL' },
  { value: 'Italy', html: 'Italy', code: 'IT' },
  { value: 'Jamaica', html: 'Jamaica', code: 'JM' },
  { value: 'Japan', html: 'Japan', code: 'JP' },
  { value: 'Jordan', html: 'Jordan', code: 'JO' },
  { value: 'Kazakhstan', html: 'Kazakhstan', code: 'KZ' },
  { value: 'Kenya', html: 'Kenya', code: 'KE' },
  { value: 'Kiribati', html: 'Kiribati', code: 'KI' },
  { value: 'Korea (North)', html: 'Korea (North)', code: 'KP' },
  { value: 'Korea (South)', html: 'Korea (South)', code: 'KR' },
  { value: 'Kuwait', html: 'Kuwait', code: 'KW' },
  { value: 'Kyrgyzstan', html: 'Kyrgyzstan', code: 'KG' },
  { value: 'Laos', html: 'Laos', code: 'LA' },
  { value: 'Latvia', html: 'Latvia', code: 'LV' },
  { value: 'Lebanon', html: 'Lebanon', code: 'LB' },
  { value: 'Lesotho', html: 'Lesotho', code: 'LS' },
  { value: 'Liberia', html: 'Liberia', code: 'LR' },
  { value: 'Libya', html: 'Libya', code: 'LY' },
  { value: 'Liechtenstein', html: 'Liechtenstein', code: 'LI' },
  { value: 'Lithuania', html: 'Lithuania', code: 'LT' },
  { value: 'Luxembourg', html: 'Luxembourg', code: 'LU' },
  { value: 'Madagascar', html: 'Madagascar', code: 'MG' },
  { value: 'Malawi', html: 'Malawi', code: 'MW' },
  { value: 'Malaysia', html: 'Malaysia', code: 'MY' },
  { value: 'Maldives', html: 'Maldives', code: 'MV' },
  { value: 'Mali', html: 'Mali', code: 'ML' },
  { value: 'Malta', html: 'Malta', code: 'MT' },
  { value: 'Marshall Islands', html: 'Marshall Islands', code: 'MH' },
  { value: 'Mauritania', html: 'Mauritania', code: 'MR' },
  { value: 'Mauritius', html: 'Mauritius', code: 'MU' },
  { value: 'Mexico', html: 'Mexico', code: 'MX' },
  { value: 'Micronesia', html: 'Micronesia', code: 'FM' },
  { value: 'Moldova', html: 'Moldova', code: 'MD' },
  { value: 'Monaco', html: 'Monaco', code: 'MC' },
  { value: 'Mongolia', html: 'Mongolia', code: 'MN' },
  { value: 'Montenegro', html: 'Montenegro', code: 'ME' },
  { value: 'Morocco', html: 'Morocco', code: 'MA' },
  { value: 'Mozambique', html: 'Mozambique', code: 'MZ' },
  { value: 'Myanmar', html: 'Myanmar', code: 'MM' },
  { value: 'Namibia', html: 'Namibia', code: 'NA' },
  { value: 'Nauru', html: 'Nauru', code: 'NR' },
  { value: 'Nepal', html: 'Nepal', code: 'NP' },
  { value: 'Netherlands', html: 'Netherlands', code: 'NL' },
  { value: 'New Zealand', html: 'New Zealand', code: 'NZ' },
  { value: 'Nicaragua', html: 'Nicaragua', code: 'NI' },
  { value: 'Niger', html: 'Niger', code: 'NE' },
  { value: 'Nigeria', html: 'Nigeria', code: 'NG' },
  { value: 'Norway', html: 'Norway', code: 'NO' },
  { value: 'Oman', html: 'Oman', code: 'OM' },
  { value: 'Pakistan', html: 'Pakistan', code: 'PK' },
  { value: 'Palau', html: 'Palau', code: 'PW' },
  { value: 'Palestine, State of', html: 'Palestine, State of', code: 'PS' },
  { value: 'Panama', html: 'Panama', code: 'PA' },
  { value: 'Papua New Guinea', html: 'Papua New Guinea', code: 'PG' },
  { value: 'Paraguay', html: 'Paraguay', code: 'PY' },
  { value: 'Peru', html: 'Peru', code: 'PE' },
  { value: 'Philippines', html: 'Philippines', code: 'PH' },
  { value: 'Poland', html: 'Poland', code: 'PL' },
  { value: 'Portugal', html: 'Portugal', code: 'PT' },
  { value: 'Qatar', html: 'Qatar', code: 'QA' },
  { value: 'Romania', html: 'Romania', code: 'RO' },
  { value: 'Russia', html: 'Russia', code: 'RU' },
  { value: 'Rwanda', html: 'Rwanda', code: 'RW' },
  { value: 'Saint Kitts and Nevis', html: 'Saint Kitts and Nevis', code: 'KN' },
  { value: 'Saint Lucia', html: 'Saint Lucia', code: 'LC' },
  {
    value: 'Saint Vincent and the Grenadines',
    html: 'Saint Vincent and the Grenadines',
    code: 'VC',
  },
  { value: 'Samoa', html: 'Samoa', code: 'WS' },
  { value: 'San Marino', html: 'San Marino', code: 'SM' },
  { value: 'Sao Tome and Principe', html: 'Sao Tome and Principe', code: 'ST' },
  { value: 'Saudi Arabia', html: 'Saudi Arabia', code: 'SA' },
  { value: 'Senegal', html: 'Senegal', code: 'SN' },
  { value: 'Serbia', html: 'Serbia', code: 'RS' },
  { value: 'Seychelles', html: 'Seychelles', code: 'SC' },
  { value: 'Sierra Leone', html: 'Sierra Leone', code: 'SL' },
  { value: 'Singapore', html: 'Singapore', code: 'SG' },
  { value: 'Slovakia', html: 'Slovakia', code: 'SK' },
  { value: 'Slovenia', html: 'Slovenia', code: 'SI' },
  { value: 'Solomon Islands', html: 'Solomon Islands', code: 'SB' },
  { value: 'Somalia', html: 'Somalia', code: 'SO' },
  { value: 'South Africa', html: 'South Africa', code: 'ZA' },
  { value: 'South Sudan', html: 'South Sudan', code: 'SS' },
  { value: 'Spain', html: 'Spain', code: 'ES' },
  { value: 'Sri Lanka', html: 'Sri Lanka', code: 'LK' },
  { value: 'Sudan', html: 'Sudan', code: 'SD' },
  { value: 'Suriname', html: 'Suriname', code: 'SR' },
  { value: 'Sweden', html: 'Sweden', code: 'SE' },
  { value: 'Switzerland', html: 'Switzerland', code: 'CH' },
  { value: 'Syria', html: 'Syria', code: 'SY' },
  { value: 'Taiwan', html: 'Taiwan', code: 'TW' },
  { value: 'Tajikistan', html: 'Tajikistan', code: 'TJ' },
  { value: 'Tanzania', html: 'Tanzania', code: 'TZ' },
  { value: 'Thailand', html: 'Thailand', code: 'TH' },
  { value: 'Timor-Leste', html: 'Timor-Leste', code: 'TL' },
  { value: 'Togo', html: 'Togo', code: 'TG' },
  { value: 'Tonga', html: 'Tonga', code: 'TO' },
  { value: 'Trinidad and Tobago', html: 'Trinidad and Tobago', code: 'TT' },
  { value: 'Tunisia', html: 'Tunisia', code: 'TN' },
  { value: 'Turkey', html: 'Turkey', code: 'TR' },
  { value: 'Turkmenistan', html: 'Turkmenistan', code: 'TM' },
  { value: 'Tuvalu', html: 'Tuvalu', code: 'TV' },
  { value: 'Uganda', html: 'Uganda', code: 'UG' },
  { value: 'Ukraine', html: 'Ukraine', code: 'UA' },
  { value: 'United Arab Emirates', html: 'United Arab Emirates', code: 'AE' },
  { value: 'United Kingdom', html: 'United Kingdom', code: 'GB' },
  { value: 'United States', html: 'United States', code: 'US' },
  { value: 'Uruguay', html: 'Uruguay', code: 'UY' },
  { value: 'Uzbekistan', html: 'Uzbekistan', code: 'UZ' },
  { value: 'Vanuatu', html: 'Vanuatu', code: 'VU' },
  { value: 'Venezuela', html: 'Venezuela', code: 'VE' },
  { value: 'Vietnam', html: 'Vietnam', code: 'VN' },
  { value: 'Yemen', html: 'Yemen', code: 'YE' },
  { value: 'Zambia', html: 'Zambia', code: 'ZM' },
  { value: 'Zimbabwe', html: 'Zimbabwe', code: 'ZW' },
]

export default countries
